# Generated by Django 4.2.5 on 2023-09-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=122)),
                ('enquiry', models.CharField(max_length=222)),
                ('date', models.DateField()),
            ],
        ),
    ]
